spring:
  datasource:
    url: jdbc:mysql://localhost:3309/ii?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false

ftp:
  ayfaar:
    ru:
      login: no
      password: no

server:
  ssl:
    key-store: D:\projects\ayfaar\ii-app\keystore.p12
    keyAlias: ii.ayfaar.org